# preload = /home/vitordeoliveira/dotfiles/hypr/Cloudsnight.jpg
# wallpaper = ,/home/vitordeoliveira/dotfiles/hypr/Cloudsnight.jpg

wallpaper {
    monitor = 
    path = /home/vitordeoliveira/dotfiles/hypr/Cloudsnight.jpg
    fit_mode = cover
}
